### ISSUE TITLE
Optional JWT validation

### ISSUE THREAD

**Issue by alexandrefavre4** [krakend/krakend-jose#108]
Hi there,

I would like to know if it is possible to configure the JWT validation to be optional:
- Access token is valid -> `sub` is forwarded via `X-User-Id` header
- Access token is invalid -> `X-User-Id` header is not added

```
{
  "alg": "RS256",
  "jwk_url": "{{ $.settings.authentication.jwtIssuer }}/.well-known/jwks",
  "issuer": "{{ $.settings.authentication.jwtIssuer }}",
  "audience": [
    "MyAudience"
  ],
  "propagate_claims": [
    ["sub", "X-User-Id"]
  ],
  "optional": true      <- Something like this
}
```

**Comment by alombarte** [comment]
Hi @alexandrefavre4,

We are not going to implement this. We don't think validation can be optional if you add the component. For this kind of logics, you should implement a [server plugin](https://www.krakend.io/docs/extending/http-server-plugins/).
