### ISSUE TITLE
Missing documentation for building and using the plugin

### ISSUE THREAD

**Issue by vgarcia-lessthanthree** [krakend/krakend-jose#138]
Hello KrakenD team,

First of all, thank you for developing and maintaining the `krakend-jose` repository. I've been exploring this implementation, and it seems like a very useful extension for KrakenD.

However, I noticed that the repository does not include a `README.md` or clear instructions on how to build and use the plugin, especially as a `.so` file for production environments. This information is crucial for users looking to extend KrakenD using custom plugins.

It would be incredibly helpful to have:

1. Step-by-step instructions for building the plugin using Go (e.g., `go build -buildmode=plugin`).
2. Details about specific dependencies or required versions (Go, modules, etc.).
3. Examples of KrakenD configuration to load the plugin (optional).
4. Best practices to ensure compatibility between the KrakenD binary and the plugin.

I understand this project may be under active development, but I believe adding such documentation would greatly improve the adoption of this extension within the community.

If you need help drafting this document, I’d be happy to contribute or provide a draft.

Thank you in advance for your attention and all the hard work you've put into this!

Best regards

**Comment by kpacha** [comment]
this repo doesn't contain a plugin (there is no main package). it contains some middlewares ready to be injected into the krakend factory stack (as you can see here: https://github.com/krakend/krakend-ce/blob/master/handler_factory.go#L27)

**Comment by kpacha** [comment]
in krakend-ce, the factory is already stacked. In order to activate it, you need to add the required configuration to your endpoints: https://www.krakend.io/docs/authorization/jwt-validation/
