### ISSUE TITLE
Expiration time for token from krakend-jose/signer

### ISSUE THREAD

**Issue by psanju** [krakend/krakend-jose#54]
I am using krakend-jose/signer for generating JWT as my backend is returning some basic info and no JWT and no expiration time as well. I am using the return value in payload. Now my queries are
1) What is the expiry time of token generated from krakend-jose/signer and how can I change it?
2) How can I generate refresh token?

Any help will be great. Thanks.

**Comment by alombarte** [comment]
The signer component only signs the fields you pass.

The content is on you. But I guess my answer after three years is not going to help you much anyway :) (sorry)
