### ISSUE TITLE
Some questions about the cache 

### ISSUE THREAD

**Issue by willie68** [krakend/krakend-jose#61]
Hi, 
it's me again. 
While working with KrakenD a few questions and requests arose regarding the cache.
1. Can you set the cache size? The documentary speaks of 100 entries. That is a little too little in our case.
2. Does the cache work across endpoints or is a separate cache built for each endpoint?

**Comment by alombarte** [comment]
Almost three years later...
This was documented long ago. Thanks for opening the issue back then.
