### ISSUE TITLE
Error with devopsfaith/krakend-jose/validator jwk-url

### ISSUE THREAD

**Issue by Dimoner** [krakend/krakend-jose#83]
Hello everyone! 
I found problem with IdentityServer4 and Krakend, when i wrote in jwk-url  {identity address}.well-known/openid-configuration/jwks, Krakend wrote to the log - "ERROR answer isn't json", but IS4 response Content-type application/jwk-set+json with current body.
Could you add suppory Content-Type  application/jwk-set+json for  jwk-url parameter?

**Comment by ramalalc** [comment]
Maybe this can help: https://github.com/krakend/krakend-ce/issues/766#issuecomment-1663794282.

There is a suggestion in a similar issue, to use a martian modifier to change the `content-type` and to workaround this problem.

**Comment by alombarte** [comment]
Hi @Dimoner ,

Although this issue is quite old, this functionality request is still on the table. We might address this on KrakenD 2.6

**Comment by dhontecillas** [comment]
this will be fixed with https://github.com/krakend/krakend-jose/pull/126

**Comment by alombarte** [comment]
Releasing with KrakenD 2.5 :)
