### ISSUE TITLE
Return WWW-Authenticate header upon 401

### ISSUE THREAD

**Issue by chibenwa** [krakend/krakend-jose#86]
The `WWW-Authenticate` mechanism allow interoperability on authentication discovery.

This is actively being used by one of my use cases, JMAP. https://jmap.io/server.html#401-unauthorized

As such, I would like to be able to have Krakend returning a `WWW-Authenticate` header but today is not the case.

![Screenshot from 2022-01-14 09-16-40](https://user-images.githubusercontent.com/6928740/149440503-18c0ce50-a298-4939-83ef-73e5dbb8dcbc.png)

**Comment by alombarte** [comment]
After a year and a half after opening this isse, I see no relevant number of upvotes in the future to introduce a new configuration component. We haven't had input from customer or users requesting this change either.
