### ISSUE TITLE
should have a JSON content type for JWKS endpoint

### ISSUE THREAD

**Issue by rjsoph** [krakend/krakend-jose#96]
I am using MacOS with the latest from brew...  I am getting this error and cannot figure out what is wrong with my jwks endpoint

[KRAKEND] 2022/09/20 - 11:47:12.156 ▶ ERROR [ENDPOINT: /geo/v1/countries][JWTValidator] Unable to validate the token: should have a JSON content type for JWKS endpoint

My endpoint (keycloak) seems to set the Content-Type: application/json so I do not know what else is required.

> GET /realms/sophware/protocol/openid-connect/certs HTTP/2
> Host: auth.sophware.com
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: awselb/2.0
< date: Tue, 20 Sep 2022 15:43:51 GMT
< content-type: application/json
< content-length: 2925

My config is as follows....

{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "KrakenD - API Gateway",
  "extra_config": {
    "security/cors": {
      "allow_origins": [
        "*"
      ],
      "expose_headers": [
        "Content-Length",
        "Content-Type"
      ],
      "max_age": "12h",
      "allow_methods": [
        "GET",
        "HEAD"
      ]
    },
    "telemetry/logging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true
    }
  },
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "endpoints": [
    {
      "endpoint": "/geo/v1/countries",
      "method": "GET",
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/geo/v1/countries",
          "is_collection": true,
          "encoding": "json",
          "sd": "static",
          "method": "GET",
          "host": [
            "https://api.sophware.com"
          ],
          "disable_host_sanitize": false
        }
      ],
      "extra_config": {
        "qos/ratelimit/router": {
          "max_rate": 0,
          "client_max_rate": 10,
          "strategy": "header",
          "key": "Authorization"
        },
        "auth/validator": {
          "alg": "RS256",
          "jwk_url": "https://auth.sophware.com/realms/sophware/protocol/openid-connect/certs",
	  "issuer": "https://auth.sophware.com/realms/sophware",
	  "operation_debug": true,
	  "cache": true
        }
      }
    },
    {
      "endpoint": "/geo/v1/features",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/geo/v1/features",
          "is_collection": true,
          "sd": "static",
          "method": "GET",
          "host": [
            "https://api.sophware.com"
          ],
          "disable_host_sanitize": false
        }
      ],
      "extra_config": {
        "qos/ratelimit/router": {
          "max_rate": 0,
          "client_max_rate": 5,
          "strategy": "ip"
        }
      }
    }
  ]
}

**Comment by friedcalamari** [comment]
Hi @rjsoph , without a token example and the contents of your JWK URL is impossible to determine what is the cause of this issue (I got a 503 Service Temporarily Unavailable). The problem is not with the krakend configuration.
